//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tur_Agentstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bronirovanie
    {
        public int ID_Bronirovania { get; set; }
        public int ID_Clienta { get; set; }
        public int ID_Tura { get; set; }
        public System.DateTime Data_broni { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tur Tur { get; set; }
    }
}
